<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="/js/indexMap.js"></script>

<aside id="featured" class="body">
    <article>
        <p>let us help you get to your destination</p>
        <div></div>
        <div id="map_canvas"></div>
        <div>
            <?php echo $this->lineSelect; ?>
        </div>
    </article>
</aside><!-- /#featured -->
