<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Cat Tracker</title>

        <link rel="stylesheet" type="text/css"
     href="<?php echo $this->baseUrl('css/main.css'); ?>" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.15/jquery-ui.min.js"></script>
        <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css" type="text/css" />        
        <link href="/css/demo_table.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/css/demo_page.css" media="screen" rel="stylesheet" type="text/css" />

        <!--[if IE]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
        <!--[if lte IE 7]>
                <script src="js/IE8.js" type="text/javascript"></script><![endif]-->
        <!--[if lt IE 7]>
        
                <link rel="stylesheet" type="text/css" media="all" href="css/ie6.css"/><![endif]-->
    </head>

    <body id="index" class="home">

        <header id="banner" class="body">
            <h1><a href="#">cattracker<br /><strong>your campus travel guide</strong></a></h1>
            <nav><ul>
                    <li class="active"><a href="/">home</a></li>
                    <li><a href="index/about">about</a></li>

                    <li><a href="/admin">admin</a></li>
                </ul></nav>

        </header><!-- /#banner -->

        <?php echo $this->layout()->content ?>


        <footer id="contentinfo" class="body">
            <address id="about" class="vcard body">
                <span class="primary">
                    <strong><a href="/" class="fn url">Cattracker</a></strong>

                    <span class="role">Campus Travel Guide</span>
                </span><!-- /.primary -->

                <span class="bio">Cat Tracker is a website that offers UCM students an efficient way to travel using the cat tracks. It was founded by Victor Lara and Francisco Velazquez.</span>

            </address><!-- /#about -->
            <p>2011 <a href="http://cattracker.net">Cat Tracker</a>.</p>
        </footer><!-- /#contentinfo -->

    </body>
</html>