<table id="arrivalsTable" class="display">
    <thead>
        <tr>
            <th>ID</th>
            <th>Location</th>
            <th>Time</th>
            <th>Line</th>
            <th>Session</th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach($this->currentArrivals as $arrivals){
                ?>
            <tr>
             <td id="<?php echo $arrivals->id;?>"><?php echo $arrivals->id;?></td>
            <td id="<?php echo $arrivals->id;?>">
                <?php
                foreach ($this->Locations as $loc){
                    if ($loc->id == $arrivals->location)
                        echo $loc->name;
                }
                ?>
            </td>
            <td id="<?php echo $arrivals->id;?>">
                <?php echo $arrivals->time;?>
            </td>
            <td id="<?php echo $arrivals->id;?>">
                <?php 
                foreach ($this->Lines as $line){
                    if ($line->id == $arrivals->line)
                        echo $line->name;
                }
                ?>
            </td>
            <td id="<?php echo $arrivals->id;?>">
                <?php 
                foreach($this->Sessions as $session){
                 if ($session->id == $arrivals->sessionID){
                     echo $session->desc;
                 }
                }
                        ?>
            </td>
        </tr>
        <?php
            }
        ?>
    </tbody>
</table>