<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript" src="/js/libs/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/js/libs/jquery.jeditable.mini.js"></script>
<script src="/js/adminLocationMap.js"></script>
<script type="text/javascript" src="/js/manageLocations.js"></script>
<script type="text/javascript" src="/js/managelines.js"></script>
<script type="text/javascript" src="/js/manageArrival.js"></script>
<style type="text/css">
                        html { height: 100% }
                        body { height: 100%; width: 94%; margin: 3%; padding: 0px }
                        #map_canvas { height: 300px }
</style>
<div id="map_canvas"></div>
    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Locations</a></li>
            <li><a href="#tabs-2">Lines</a></li>
            <li><a href="#tabs-3">Arrivals</a>
        </ul>
        <div id="tabs-1">
            <?php 
                $this->formLocation->setAction('/Admin/managelocations');
                echo $this->formLocation;
                echo $this->partial("partials/locationstable.phtml",array("Locations"=>$this->Locations));
            ?>
            <a href="javascript:void(0)" id="deleteLoc">Delete selected location</a>
        </div>
        <div id="tabs-2">
            <?php
                $this->formLine->setAction('/Admin/managelines');
                echo $this->formLine;
                echo $this->partial("partials/linestable.phtml",array("currentLines"=>$this->currentLines));
            ?>
            <a href="javascript:void(0)" id="deleteLine">Delete selected line</a>
        </div>
        <div id="tabs-3">
            <?php
                $this->formArrival->setAction('/Admin/managearrival');
                echo $this->formArrival;
                echo $this->partial("partials/arrivalstable.phtml", array("currentArrivals"=>$this->arrivals));
            ?>
        </div>
</div>
