<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript" src="/js/libs/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/js/libs/jquery.jeditable.mini.js"></script>
<script src="/js/adminLocationMap.js"></script>
<script type="text/javascript" src="/js/manageLocations.js"></script>
<script type="text/javascript" src="/js/managelines.js"></script>
<style type="text/css">
                        html { height: 90% }
                        body { height: 80%; margin: 0px; padding: 0px }
                        #map_canvas { height: 300px }
                        #container {
                                width: 80%;  /* this will create a container 80% of the browser width */
                                /* height: 100% */
                                margin: 0 auto; /* the auto margins (in conjunction with a width) center the page */
                        }
</style>
<div id="map_canvas"></div>
<div id="tabs">
    <ul>
        <li><a href="#tabs-1">Locations</a></li>
        <li><a href="#tabs-2">Lines</a></li>
    </ul>
<!--    <h3 class="trigger"><a href="#">Locations</a></h3>-->
    <div id="tabs-1" class="toggle_container">
        <div class="block">
    <?php 
    $this->formLocation->setAction('/Admin/managelocations');
    echo $this->formLocation;
    ?>
    <table id="locationsTable" class="display">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Latitude</th>
                <th>Longitude</th>
            </tr>
        </thead>
        <tbody>
    <?php
    foreach($this->Locations as $loc){
        ?>
        <tr>
            <td id="<?php echo $loc->id;?>">
                <?php echo $loc->name;?>
            </td>
            <td id="<?php echo $loc->id;?>">
                <?php echo $loc->description;?>
            </td>
            <td id="<?php echo $loc->id;?>">
                <?php echo $loc->lat;?>
            </td>
            <td id="<?php echo $loc->id;?>">
                <?php echo $loc->lng;?>
            </td>
        </tr>
        <?php
    }
    ?>
        </tbody>
    </table>
    <a href="javascript:void(0)" id="deleteLoc">Delete selected location</a>
    
    </div>
    </div>
<!--<h3 class="trigger"><a href="#">Lines</a></h3>-->
<div id="tabs-2"class="toggle_container">
    <div class="block">
    <?php
    $this->formLine->setAction('/Admin/managelines');
    echo $this->formLine;
    ?>
    <?php
    echo $this->partial("partials/linestable.phtml",array("currentLines"=>$this->currentLines));
    ?>
    <a href="javascript:void(0)" id="deleteLine">Delete selected line</a>
    <div id="dialog-confirmLine" title="Delete Action" class="dialog-confirmLine" style="display:none">
        <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>The Line will be removed. Are you sure?</p>
    </div>
    </div>
</div>
</div>
