<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript" src="/js/libs/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/js/libs/jquery.jeditable.mini.js"></script>
<script src="/js/adminLocationMap.js"></script>
<script type="text/javascript" src="/js/manageLocations.js"></script>
<script type="text/javascript" src="/js/managelines.js"></script>
<style type="text/css">
                        html { height: 100% }
                        body { height: 100%; margin: 0px; padding: 0px }
                        #map_canvas { height: 50% }
                        #container {
                                width: 80%;  /* this will create a container 80% of the browser width */
                                /* height: 100% */
                                margin: 0 auto; /* the auto margins (in conjunction with a width) center the page */
                        }
</style>
<div id="map_canvas"></div>
<table id="locationsTable" class="display">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Latitude</th>
            <th>Longitude</th>
        </tr>
    </thead>
    <tbody>
<?php
foreach($this->Locations as $loc){
    ?>
    <tr>
        <td id="<?php echo $loc->id;?>">
            <?php echo $loc->name;?>
        </td>
        <td id="<?php echo $loc->id;?>">
            <?php echo $loc->description;?>
        </td>
        <td id="<?php echo $loc->id;?>">
            <?php echo $loc->lat;?>
        </td>
        <td id="<?php echo $loc->id;?>">
            <?php echo $loc->lng;?>
        </td>
    </tr>
    <?php
}
?>
    </tbody>
</table>
<h3><a href="javascript:void(0)" id="delete">Delete selected location</a></h3>
<?php 
$this->formLocation->setAction('/Admin/managelocations');
echo $this->formLocation;
?>

<h2>Current lines</h2>
<?php
echo $this->partial("partials/linestable.phtml",array("currentLines"=>$this->currentLines));
?>
<h3><a href="javascript:void(0)" id="delete">Delete selected line</a></h3>

<h2>Please use the form below to create a new line</h2>

<?php
$this->formLine->setAction('/Admin/managelines');
echo $this->formLine;
?>
<div id="dialog-confirmLine" title="Delete Action" class="dialog-confirmLine" style="display:none">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>The Line will be removed. Are you sure?</p>
</div>

